### ISSUE TITLE
Hero Image Wont Go To Top / Nav Bar Links Move When Hovered Over

### ISSUE THREAD

**Issue by ryanpurdyca** [ryanpurdyca/project-dark#1]
Hey @Thomasjbradley I started making this site last night in my spare time for fun, and I came across a few issues I couldn't figure out how to solve. Any input you could provide would be greatly appreciated thank you!

Main Issues:
-Hero image wont go to top and leaves an ugly white space
-Hamburger menu options shift right when hovered over

**Comment by thomasjbradley** [comment]
_Re: hero moving to top_

The `<header>` tag has the class of `.unit` on it that isn't necessary because it isn't inside a `.grid`.

---

_Re: shifting navigation_

It's because they have a `width` only on `:hover`.
